### PR TITLE
won't accept profane game or username names

### PR DESCRIPTION
**Pull request by mattwhite180**
User cannot create or join a game with a profane game name or profane username

### CODE REVIEW

**Comment by hhenrichsen** [comment]
It'd be good to see some unit tests on this before we merge it in.

**Comment by mattwhite180** [comment]
> 
> 
> It'd be good to see some unit tests on this before we merge it in.

All of the logic in the profanity check is in a repo I forked (github.com/mattwhite180/go-away) that has 96.7% test coverage

**Comment by mattwhite180** [comment]
> 
> 
> Please add some unit tests which show that we don't have (too bad of) a Scunthorpe problem. A good list of strings to try can be found here: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt#L681

Thank you for the list! They have been added to the code.  I do have some unit tests for Scunthorpe problems at the bottom of https://github.com/mattwhite180/go-away/blob/master/goaway_test.go

**Comment by jak103** [comment]
@mattwhite180 you should submit a pull request to the original go-away author. (probably don't remove all his profanities)

**Pull request merged**
