### PR TITLE
Get current user's player data from the database and not the game state

### PR DESCRIPTION
**Pull request by gitdaddy**
Resolves issue: [#167](https://github.com/jak103/uno/issues/167)

### CODE REVIEW

**Comment by jak103** [comment]
I'm not sure I want this split to be done. In my mind, the player should be in the game state. If we make this split, you are essentially treating the "Player" model like we actually want to treat an "Account" model. One "Account" per human, but multiple "Player" models per "Account". Thoughts?

**Comment by logan-hendricks** [comment]
@jak103 As the one who wrote the issue for this... I personally assumed that when I included `my_player` data in the gameState... that was more of a hack to get the system running. This issue was formed after a conversation with @Aaron-Fine  around [this PR](https://github.com/jak103/uno/pull/155/files).  

Aaron argued in this case that the player should be separate from the game. In our conversation, I expressed that I was unsure if the data revolving around `playerData` in the gameState really should be there, or should have been separate.  In retrospect, I should have taken the time to consult where we stood a team on the decision.  

At the time, I decided that Aaron was probably more `idealotically` correct, and approve his PR, and created the linked issue to further expand his idea.

However, definitely open to the team thinking otherwise.  I apologize for any churn this caused in not confirming the issue before making it.

**Comment by gitdaddy** [comment]
I'm kind of leaning towards what @jak103 is saying since it moves away from keeping the game state central. This also incurs the overhead of updating the player in the database for every action they do. Perhaps we can close this as a non-issue?

**Comment by Aaron-Fine** [comment]
@jak103, what you are proposing sounds reasonable to me. I think, thought, that we are really just struggling with terminology and in putting the right pieces of data into the right spots.

Here is a first swag at trying to add that clarity:
```
Account
  display name
  account id

Player
  account id
  hand
  (game id is implied through being attached to a particular game state)

Game
  players []
  watchers [] (Watchers are separate from players to make it easy to tell that the same account isn't both playing and watching)
  game name
  deck data
```

One of the implications of this approach, to me, is that we should have different endpoints for dealing with each of these three data structures in the server.

**Pull request closed without merging**
