### PR TITLE
workaround to keep volume mount

### PR DESCRIPTION
**Pull request by logan-hendricks**
This only works specifically for the constraints of this project.

How this works
------------------------------- 

1. Pre-create a directory in the docker image
2. Install all of the required dependencies into that directory
3. Create a synonymous directory on the host (I put the .gitignore file there in order to have the directory checked into git, but to ensure all contents inside the directory don't get pushed)
4. establish a volume on the service in the `docker-compose` file that only designates a directory inside the container. 

Basically, by pre-creating a directory, the host knows the directory should exist, and the image just fills it up. However. the files inside the directory don't ever map back to the host.  Basically, the directory exists in both places, but can have completely different contents in either place.

**CONS of this approach**
- Basically its like Las Vegas
- Whatever you do in the image stays in the image
- Whatever you do in the host stays on the host
- The directory must exist in both locations for it to work

**PROS of this approach**
- Dependency management is done at image build time.
- People don't need to install NPM
- Basically it does what Jacob wanted it to do.... for the most part. Otherwise the host always just overwrites the contents of the directory

-

### CODE REVIEW

**Comment by jak103** [comment]
Just had another idea for fixing this. What if on the docker-compose.yml
line we had the command be npm install && npm run-script serve

That would cause the install to run and launch the front end server.

Thoughts?

**Comment by logan-hendricks** [comment]
hmm.......... I'm trying to think of the pros & cons of that....

It would certainly guarantee people wouldn't forget to do the npm install.... but it does cause an initial boot up of a lot longer.

I feel however it would be a lot easier to maintain than always doing it through the docker image.... 

I'm down with that. Give me 10 minutes.

**Comment by logan-hendricks** [comment]
@jak103 Those changes have been implemented. Let me know if you have any thoughts on them.

**Comment by jak103** [comment]
Guess what I found! Anonymous volume is the secret.
[image: image.png]

**Comment by jak103** [comment]
image

**Comment by logan-hendricks** [comment]
That's pretty much what I did when I started this PR. I genuinely can't remember now why we didn't go with that solution? I think the problem was that it just stayed exclusively inside the docker image, it didn't interact with the host file directory at all.

**Pull request merged**
