### PR TITLE
Separate packages

### LINKED ISSUE #181: Decouple all of the different go files into the correct packages
We have been building almost all of `server` using the `main` package. This likely should not be the case. While there are a couple of different ways we could break up the packages. I currently propose the following.

- **service**
  - uno.go
  - deckUtils.go
- **route**
  - routeHandlers.go
  - jwt.go

This issue is entirely up for debate and review from the team. If others have different opinions on how this should be structures. **Speak now or forever hold your peace**

### PR DESCRIPTION
**Pull request by hhenrichsen**
Closes #181. This will require everyone to re-pull dev before they do their issues.

### CODE REVIEW

**Comment by hhenrichsen** [comment]
Looks like this is missing some imports for tests. I'll get to fixing them.

**Comment by logan-hendricks** [comment]
@hhenrichsen I can be wrong, but I'd personally like to see the chat feature moved in and the card images moved in before pushing in this feature. I think it should be done asap, but as both of those features have had to re-merge in dev multiple times. I'd personally like to see those just merged in before making them have to resolve this change.

**Comment by hhenrichsen** [comment]
@logan-hendricks Have the other PRs been merged in? I think this is now up to date with dev. We can also probably merge #196 in at the same time.

**Comment by jak103** [comment]
I agree with Logan on this one. Let the other teams finish before we make everyone remerge.

**Comment by logan-hendricks** [comment]
@hhenrichsen I was just wondering about getting yours in now. We've merged in a couple of the PR's now and the only change I was potentially waiting on is the help button. but that one is a frontend only change.

All of the changes that are specific to the backend are currently merged in. I wouldn't be opposed to making this change now as I don't see anything currently in flight.

**Comment by hhenrichsen** [comment]
I talked about this on the Discord, but I think I'm okay leaving this as is for now and letting everyone finish up their work. I can re-make these changes pretty easily.

**Comment by hhenrichsen** [comment]
Closing until the rest of this project is more ready for this refactor.

**Pull request closed without merging**
